//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterynaryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AestheticService
    {
        public string IDAestheticService { get; set; }
        public Nullable<System.DateTime> AestheticServiceDate { get; set; }
        public string AestheticrviceDescription { get; set; }
        public string AestheticServicEstatus { get; set; }
        public string IDPet { get; set; }
        public string IDDoctor { get; set; }
    
        public virtual Estatus Estatus { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Pet Pet { get; set; }
    }
}
