//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterynaryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetVaccine
    {
        public string IDPet { get; set; }
        public string IDVaccine { get; set; }
        public Nullable<System.DateTime> VaccinationDate { get; set; }
    
        public virtual Pet Pet { get; set; }
        public virtual Vaccine Vaccine { get; set; }
    }
}
